DOCS: Upgrade Sphinx Theme to version 1.x
scylladb/java-driver pull request #101
Opened 2021-10-12 10:36 UTC by lauranovich

This PR upgrades the Sphinx theme to version 1.x

2021-10-12 12:16 UTC, lauranovich commented
@dgarcia360 can you please review?

2021-10-13 08:51 UTC, dgarcia360 commented on .github/workflows/docs-pages@v2.yaml
> +      - "docs/**"
```suggestion
on:
  push:
    branches:
    - scylla-3.x
    paths:
    - 'docs/**'
    - 'faq/**'
    - 'manual/**'
    - 'changelog/**'
    - 'upgrade_guide/**'
```

2021-10-13 08:51 UTC, dgarcia360 commented on .github/workflows/docs-pages@v2.yaml
> +      - "docs/**"
This project does not have a master branch, it's named "scylla-3.x".

2021-10-13 08:52 UTC, dgarcia360 commented on .github/workflows/docs-pr@v1.yaml
> +      - "docs/**"
```suggestion
on:
  pull_request:
    branches:
    - scylla-3.x
    paths:
    - 'docs/**'
    - 'faq/**'
    - 'manual/**'
    - 'changelog/**'
    - 'upgrade_guide/**'
```

2021-10-13 08:54 UTC, dgarcia360 commented on .github/workflows/docs-pages@v2.yaml
> +          python-version: 3.7
```suggestion
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
```

2021-10-13 08:54 UTC, dgarcia360 commented on .github/workflows/docs-pages@v2.yaml
> +          python-version: 3.7
This repo requires JDK to build their reference documentation.

2021-10-13 10:55 UTC, dgarcia360 commented on docs/source/conf.py
> +    'hide_sidebar_index': 'False',
```suggestion
    'hide_sidebar_index': 'false',
```

Should work as is too, but best if we put it in lowercase as we have done in other projects.

2021-10-13 10:58 UTC, dgarcia360 approved these changes

2021-10-13 12:14 UTC, tzach approved these changes

2021-10-22 12:39 UTC, dgarcia360 reviewed
(comment deleted)

2021-10-22 12:39 UTC, dgarcia360 requested changes
This PR was replaced by https://github.com/scylladb/java-driver/pull/103, please close this one.

2021-10-25 09:03 UTC, tzach commented
@avelanarius can you please take a look?

2021-11-02 12:10 UTC, closed without merging