docs: forward-ports from 3.x
scylladb/java-driver pull request #256
Opened 2023-11-09 07:42 UTC by tchaikov

in order to build docs from 4.x branch, we have to have https://github.com/scylladb/java-driver/commit/cdaf75a6cf54b91f3f795aa509cf836166dad1e2. but since we are here, let's forward-port all 3.x doc change to 4.x. 

tested using 

```console
$ make setup
$ make preview
```

2023-11-09 07:48 UTC, tchaikov commented
/cc @dgarcia360 @annastuchlik

2024-01-04 19:30 UTC, roydahan commented
Need to rebase PR in order to re-run the CI.

2024-01-05 01:08 UTC, tchaikov commented
rebased and repushed.

2024-01-15 15:36 UTC, avelanarius commented
@dgarcia360 @annastuchlik Please review this PR.

@tchaikov I'm not really sure I understand the reasoning for this PR. The cover letter doesn't really explain the intention.

2024-01-15 15:47 UTC, tchaikov commented
> @dgarcia360 @annastuchlik Please review this PR.
> 
> @tchaikov I'm not really sure I understand the reasoning for this PR. The cover letter doesn't really explain the intention.

@avelanarius hi Piotr, the document on 4.x branch does not build without this changeset. that's why i ported the change to address the FTBFS.

2024-02-02 12:51 UTC, dgarcia360 commented
@annastuchlik @tchaikov @avelanarius  It looks good to me. The issue is that, without these changes, the 4.x will not build locally.

2024-06-13 18:20 UTC, roydahan commented
Ping reviewers

2024-07-09 10:39 UTC, Bouncheck requested changes
I successfully ran `make preview` after checking out this branch, however I've seen that script had to downgrade a lot of dependencies. Maybe a rebase is needed.
Github workflows seem incorrect or unnecessary: do we do docs deploy from 4.x branch? Deploy.sh seems not to be there anyway.
Is this purely a port? CustomCommonMarkParser seems to be new, do we not need it in 3.x?

2024-07-09 10:39 UTC, Bouncheck commented on .github/workflows/docs-pages.yaml
> +    - scylla-3.x
This feels wrong. Wouldn't that never fire?

2024-07-09 10:39 UTC, Bouncheck commented on .github/workflows/docs-pr.yaml
> +    - scylla-3.x
Similar as above. We should not have a workflow for PRs to 3.x on 4.x branch.

2024-07-09 10:44 UTC, Bouncheck commented
How do we maintain those two docs branches going forward? Is it possible to make it so we keep up to date setup on `scylla-3.x` and from time to time copy whole `docs` subdirectory to `scylla-4.x`?

2024-07-11 03:50 UTC, tchaikov commented
> I successfully ran `make preview` after checking out this branch, however I've seen that script had to downgrade a lot of dependencies. Maybe a rebase is needed. 

sure. rebased.

> Github workflows seem incorrect or unnecessary: do we do docs deploy from 4.x branch? 

i didn't manually edit the backport commits unless i had to to resolve the conflicts or to fix the document build. the purpose of this changeset is to enable us to build document on 3.x branch. i am not sure if we deploy docs from 4.x branch. guess this is a question to the maintainer of this project.

considering this PR has been around for half a year, can we get this changeset reviewed and then work on the CI of document deployment if this is desirable?

> Deploy.sh seems not to be there anyway. Is this purely a port? 

yes, it is a backport. but again, this PR has been around for ages. and i haven't cherry-picked new changes from 4.x since i sent it for review. if something is odd. the reason is very likely that it's caused by merge conflict or missing commits from 4.x. 

> CustomCommonMarkParser seems to be new, do we not need it in 3.x? Branchest/Tags need an update: latest tag is 4.18.0.1

on the contrary, it is old. the change removing `CustomCommonMarkParser` landed in 9eedcaca09d1bb5bb87452389c1eb9cc1bd9645f

2024-07-11 03:53 UTC, tchaikov commented
v2:

- cherry-pick more changes to `docs/source/conf.py`  from 4.x

2024-07-11 03:56 UTC, tchaikov commented
> How do we maintain those two docs branches going forward?

again, i think it's up to the maintainer of this project.

>  Is it possible to make it so we keep up to date setup on `scylla-3.x` and from time to time copy whole `docs` subdirectory to `scylla-4.x`?

i don't think to "copy" the whole `docs` subdirectory to `scylla-4.x` branch is the right approach. my 2 cents would be

1. get the 4.x doc build in shape, so that it can at least build
2. decide if / how to deploy it
3. setup the CI to backport and deploy it
4. add the proper label when sending doc patches to 3.x, and let CI to backport the change.

2024-07-12 02:29 UTC, tchaikov commented
@Bouncheck hi Wojciech, could you please take another look?

2024-07-12 13:00 UTC, Bouncheck commented
`make clean preview` looks better. Now manual pages can be browsed normally (before they did not work). API Documentation does not link to javadoc.

`make clean multiversionpreview` does not build correctly for me. For testing I've removed all but 2 versions (4.14.1.x and 4.15.0.x) from `BRANCHES` in source/conf.py to speed up the build.  I'm getting a 404 error page instead.
Throughout the build I'm getting a lot of lines like this one, after "updating environment" step:
```
updating environment: [new config] 102 added, 0 changed, 0 removed
/home/wo/.cache/pypoetry/virtualenvs/java-driver-xPfC9vS5-py3.11/lib/python3.11/site-packages/recommonmark/parser.py:75: UserWarning: Container node skipped: type=document
  warn("Container node skipped: type={0}".format(mdnode.t))
/home/wo/.cache/pypoetry/virtualenvs/java-driver-xPfC9vS5-py3.11/lib/python3.11/site-packages/recommonmark/parser.py:75: UserWarning: Container node skipped: type=document
  warn("Container node skipped: type={0}".format(mdnode.t))
```
Visiting the `127.0.01:5500` directs me to `http://127.0.0.1:5500/master` which has 404 error. However pages like `http://127.0.0.1:5500/stable/index.html` or `http://127.0.0.1:5500/scylla-4.15.0.x/` remain functional with redirects to javadoc when clicking on API Documentation header too.

> >    Branchest/Tags need an update: latest tag is 4.18.0.1
>
>could you be more specific? which files shall i update?
I was guessing that we'd need to just add '4.18.0.1' to `TAGS` in docs/source/conf.py but that actually breaks the build with multiple warnings like:
```
/tmp/tmpk4aq9ak4/970452ef5b72d76b4f783335fccabe57107d9735/docs/source/manual/core/pooling/index.md: WARNING: document isn't included in any toctree
```
So after all let's not do that for now.

2024-07-13 04:28 UTC, tchaikov commented
> `make clean preview` looks better. Now manual pages can be browsed normally (before they did not work). API Documentation does not link to javadoc.
> 
> `make clean multiversionpreview` does not build correctly for me. For testing I've removed all but 2 versions (4.14.1.x and 4.15.0.x) from `BRANCHES` in source/conf.py to speed up the build. I'm getting a 404 error page instead. Throughout the build I'm getting a lot of lines like this one, after "updating environment" step:
> 

i commented out "multiversionpreview" to workaround a dependency issue on python 3.12, but forgot to revert it. so the multiversion should be back now.

> ```
> updating environment: [new config] 102 added, 0 changed, 0 removed
> /home/wo/.cache/pypoetry/virtualenvs/java-driver-xPfC9vS5-py3.11/lib/python3.11/site-packages/recommonmark/parser.py:75: UserWarning: Container node skipped: type=document
>   warn("Container node skipped: type={0}".format(mdnode.t))
> /home/wo/.cache/pypoetry/virtualenvs/java-driver-xPfC9vS5-py3.11/lib/python3.11/site-packages/recommonmark/parser.py:75: UserWarning: Container node skipped: type=document
>   warn("Container node skipped: type={0}".format(mdnode.t))
> ```

we have the same error on 3.x branch.

> 
> Visiting the `127.0.0.1:5500` directs me to `http://127.0.0.1:5500/master` which has 404 error. However pages like `http://127.0.0.1:5500/stable/index.html` or `http://127.0.0.1:5500/scylla-4.15.0.x/` remain functional with redirects to javadoc when clicking on API Documentation header too.
> 

i think this is due to the removed multiversion in previous reversion. and should be fixed.

> > > Branchest/Tags need an update: latest tag is 4.18.0.1
> > 
> > 
> > could you be more specific? which files shall i update?
> 
> I was guessing that we'd need to just add '4.18.0.1' to `TAGS` in docs/source/conf.py but that actually breaks the build with multiple warnings like:
> 

yeah, all 4.x tags are broken at this moment. i think the first step is to fix the 4.x branch.

> ```
> /tmp/tmpk4aq9ak4/970452ef5b72d76b4f783335fccabe57107d9735/docs/source/manual/core/pooling/index.md: WARNING: document isn't included in any toctree
> ```
> 
> So after all let's not do that for now.

2024-07-13 04:32 UTC, tchaikov commented
v3:

- revert the change to remove multiversion support.

2024-07-16 08:58 UTC, tchaikov commented
@Bouncheck i see you are still asking for changes. may i learn what exactly the changes i need to make?

2024-07-16 09:32 UTC, Bouncheck commented
I'm not getting redirected to javadoc when clicking on API Documentation on generated page (`make clean preview`).
But if that's intended for now I can approve anyway since this PR is a big improvement.

2024-07-16 11:58 UTC, tchaikov commented
> I'm not getting redirected to javadoc when clicking on API Documentation on generated page (`make clean preview`). 

to my best knowledge, this is indeed intended. see https://github.com/scylladb/java-driver/blob/9eedcaca09d1bb5bb87452389c1eb9cc1bd9645f/docs/source/conf.py#L174-L179

we redirect the api doc to `${version_name}/api/index.html`, and if `version_name` is 14.5.6, then the link points to `/14.5.6/api/index.html`, right under the root directory. i think this should work if the html is deployed to a web server.

> But if that's intended for now I can approve anyway since this PR is a big improvement. I haven't checked this on 3.x branch but if it's the same there it would make sense to me to approve now and have a separate fix for 3.x + port to 4.x later on.

i'd appreciate if you could help approve and merge this change. based on this change, we would be able to improve the 4.x document further.

2024-07-16 13:44 UTC, Bouncheck approved these changes

2024-07-24 12:59 UTC, merged