Warn if consistency level is overridden
scylladb/java-driver pull request #325
Opened 2024-08-22 23:29 UTC by dkropachev

Closes https://github.com/scylladb/java-driver/issues/304

2024-08-26 14:12 UTC, Bouncheck requested changes
I've left a comment on DefaultPrepareRequest file

2024-08-26 14:12 UTC, Bouncheck commented on core/src/main/java/com/datastax/oss/driver/internal/core/cql/DefaultPrepareRequest.java
> +
I don't think this is the case outside of batch statements. I haven't verified that but `SyncCqlSession.prepare` says that given:
```
SimpleStatement simpleStatement = SimpleStatement.newInstance("...");
PreparedStatement preparedStatement = session.prepare(simpleStatement);
BoundStatement boundStatement = preparedStatement.bind();
```
the `boundStatement.getConsistencyLevel()` will return the same value as on `simpleStatement`.
`BoundStatementSimulacronIT.should_use_consistencies_from_simple_statement()` should verify that the consistency level is inherited.
DefaultPrepareRequest also has 
```
public ConsistencyLevel getConsistencyLevelForBoundStatements() {
    return statement.getConsistencyLevel();
  }
  ```

2024-08-27 01:39 UTC, dkropachev commented on core/src/main/java/com/datastax/oss/driver/internal/core/cql/DefaultPrepareRequest.java
> +
You are correct, removed from the PR.

2024-08-27 12:10 UTC, Bouncheck approved these changes

2024-08-27 12:16 UTC, merged