Draft
scylladb/java-driver pull request #341
Opened 2024-09-10 14:19 UTC by Bouncheck

2024-09-19 20:33 UTC, dkropachev commented
@Bouncheck , I have been thinking about this solution, more I think less I like it.
This solution to feed hosts to controll connection when it reconnects looks hacky to me. 
I think driver should sync initial contact points to the list of nodes on node events (UP/DOWN/ADD/DEL).
Let's discuss it

2024-10-08 08:54 UTC, dkropachev requested changes

2024-10-08 08:54 UTC, dkropachev commented on integration-tests/src/test/java/com/datastax/oss/driver/core/resolver/MockResolverIT.java
> +  @Test
Can you please mark this test as reproduction to make sure we don't run it

2024-10-08 08:54 UTC, dkropachev commented on core/src/main/java/com/datastax/oss/driver/api/core/config/DefaultDriverOption.java
> +      "advanced.control-connection.reconnection.fallback-to-original-contacts"),
```suggestion
      "advanced.control-connection.reconnection.fallback-to-original-contact-points"),
```

2024-10-08 08:54 UTC, dkropachev commented on integration-tests/src/test/java/com/datastax/oss/driver/core/resolver/MockResolverIT.java
> +       */
Do you need this code ?

2024-10-08 08:54 UTC, dkropachev commented on core/src/main/java/com/datastax/oss/driver/internal/core/metadata/LoadBalancingPolicyWrapper.java
> +    Queue<Node> regularQueryPlan = newQueryPlan();
I believe you can drop `newQueryPlan();` at all

2024-10-08 08:56 UTC, dkropachev commented
@Bouncheck , I see that you still use `newQueryPlan` at one particular place, can you please switch to `newControlReconnectionQueryPlan`
```
        Queue<Node> nodes = context.getLoadBalancingPolicyWrapper().newQueryPlan();
```

2024-10-08 08:57 UTC, dkropachev commented
> @Bouncheck , I have been thinking about this solution, more I think less I like it. This solution to feed hosts to controll connection when it reconnects looks hacky to me. I think driver should sync initial contact points to the list of nodes on node events (UP/DOWN/ADD/DEL). Let's discuss it.

Regarding this, I have tried to do it, unfortunately due to the API this fix will be extremely intrusive, let's go ahead with your solution.

2024-10-08 09:05 UTC, Bouncheck commented
> @Bouncheck , I see that you still use `newQueryPlan` at one particular place, can you please switch to `newControlReconnectionQueryPlan`
> 
> ```
>         Queue<Node> nodes = context.getLoadBalancingPolicyWrapper().newQueryPlan();
> ```

Yes, but it's during the initialization. I believe that part works fine.

2024-10-08 09:10 UTC, Bouncheck commented on core/src/main/java/com/datastax/oss/driver/internal/core/metadata/LoadBalancingPolicyWrapper.java
> +    Queue<Node> regularQueryPlan = newQueryPlan();
Why? Don't we want the driver to choose the hosts as policy dictates as long as the cluster is healthy?

2024-10-08 09:18 UTC, dkropachev commented
> > @Bouncheck , I see that you still use `newQueryPlan` at one particular place, can you please switch to `newControlReconnectionQueryPlan`
> > ```
> >         Queue<Node> nodes = context.getLoadBalancingPolicyWrapper().newQueryPlan();
> > ```
> 
> Yes, but it's during the initialization. I believe that part works fine.

It works fine, but creates unnecessary confusion.

2024-10-08 09:19 UTC, dkropachev commented on core/src/main/java/com/datastax/oss/driver/internal/core/metadata/LoadBalancingPolicyWrapper.java
> +    Queue<Node> regularQueryPlan = newQueryPlan();
I just mean that instead of calling `newQueryPlan()` to call `newQueryPlan(null, DriverExecutionProfile.DEFAULT_NAME, null)` here

2024-10-08 10:46 UTC, Bouncheck commented on core/src/main/java/com/datastax/oss/driver/api/core/config/DefaultDriverOption.java
> +      "advanced.control-connection.reconnection.fallback-to-original-contacts"),
Adjusted as suggested

2024-10-08 10:46 UTC, Bouncheck commented on integration-tests/src/test/java/com/datastax/oss/driver/core/resolver/MockResolverIT.java
> +       */
Removed it

2024-10-08 10:47 UTC, Bouncheck commented on core/src/main/java/com/datastax/oss/driver/internal/core/metadata/LoadBalancingPolicyWrapper.java
> +    Queue<Node> regularQueryPlan = newQueryPlan();
Replaced that call with the explicit one

2024-10-08 11:43 UTC, Bouncheck commented
I moved back that 1 call in ControlConnection init back to `newQueryPlan()`. I forgot that this change would require changing around 20 test methods which expect that exact api call

2024-10-08 11:50 UTC, Bouncheck commented
I can adjust them, but I don't know if it's worth it

2024-10-08 13:46 UTC, dkropachev commented on integration-tests/src/test/java/com/datastax/oss/driver/core/resolver/MockResolverIT.java
> +       */
Still see it.

2024-10-08 13:46 UTC, dkropachev commented
> I can adjust them, but I don't know if it's worth it

Please check last commit and tell if you are ok with it.

2024-10-08 13:56 UTC, Bouncheck commented on integration-tests/src/test/java/com/datastax/oss/driver/core/resolver/MockResolverIT.java
> +       */
Reappeared during rebase, removed it again

2024-10-08 14:08 UTC, dkropachev approved these changes

2024-10-08 14:56 UTC, merged