3.x: Add integration test for zero token nodes
scylladb/java-driver pull request #399
Opened 2024-12-09 21:00 UTC by Bouncheck

Adds ZeroTokenNodesIT that checks the behaviour of the driver when zero-token nodes are involved. Currently has one method `should_ignore_zero_token_peer` in which driver expects a normal contact point and as a result it should not populate the metadata with zero-token node from the peers table.

2024-12-10 01:44 UTC, dkropachev requested changes
@Bouncheck , thanks, looks good, could you please add another test for `Zero-token Datacenter` from https://github.com/scylladb/java-driver/issues/317

2024-12-10 01:44 UTC, dkropachev commented on driver-core/src/test/java/com/datastax/driver/core/ZeroTokenNodesIT.java
> +  public void should_ignore_zero_token_peer() {
```suggestion
  public void should_ignore_single_zero_token_peer() {
```

2024-12-11 14:54 UTC, dkropachev commented
@Bouncheck , please consider fixing code not to log following error:
```
WARN  [cluster1-worker-2] 2024-09-17 16:10:28,825 ReplicationStategy.java:204 - Error while computing token map for keyspace keyspace1 with datacenter eu-northscylla_node_north: could not achieve replication factor 3 (found 0 replicas only), check your keyspace replication settings.
```

2024-12-12 10:20 UTC, Bouncheck commented
Added some tests. The current version slightly differs from what's proposed in #317 , for example driver won't fail when executing queries after connecting to zero-token DC. It just won't direct queries to it.

2024-12-12 10:22 UTC, Bouncheck commented
> @Bouncheck , please consider fixing code not to log following error:
> 
> ```
> WARN  [cluster1-worker-2] 2024-09-17 16:10:28,825 ReplicationStategy.java:204 - Error while computing token map for keyspace keyspace1 with datacenter eu-northscylla_node_north: could not achieve replication factor 3 (found 0 replicas only), check your keyspace replication settings.
> ```



> @Bouncheck , please consider fixing code not to log following error:
> 
> ```
> WARN  [cluster1-worker-2] 2024-09-17 16:10:28,825 ReplicationStategy.java:204 - Error while computing token map for keyspace keyspace1 with datacenter eu-northscylla_node_north: could not achieve replication factor 3 (found 0 replicas only), check your keyspace replication settings.
> ```

In one of the tests i create a table in a new keyspace with general replication_factor in multi-dc setting and I do not see this error now.

2024-12-12 10:51 UTC, Bouncheck commented
Some of the tests fail, because their hosts have `null` tokens but are not meant to be treated as zero-token nodes. This needs more or different adjustments.

2024-12-19 13:19 UTC, closed without merging